apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: skaffold
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*.yaml
build:
  local:
    push: false
  artifacts:
    - image: yijiao/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: yijiao/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: yijiao/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
